\documentclass{article}\usepackage[]{graphicx}\usepackage[]{xcolor}
% maxwidth is the original width if it is less than linewidth
% otherwise use linewidth (to make sure the graphics do not exceed the margin)
\makeatletter
\def\maxwidth{ %
  \ifdim\Gin@nat@width>\linewidth
    \linewidth
  \else
    \Gin@nat@width
  \fi
}
\makeatother

\definecolor{fgcolor}{rgb}{0.345, 0.345, 0.345}
\newcommand{\hlnum}[1]{\textcolor[rgb]{0.686,0.059,0.569}{#1}}%
\newcommand{\hlsng}[1]{\textcolor[rgb]{0.192,0.494,0.8}{#1}}%
\newcommand{\hlcom}[1]{\textcolor[rgb]{0.678,0.584,0.686}{\textit{#1}}}%
\newcommand{\hlopt}[1]{\textcolor[rgb]{0,0,0}{#1}}%
\newcommand{\hldef}[1]{\textcolor[rgb]{0.345,0.345,0.345}{#1}}%
\newcommand{\hlkwa}[1]{\textcolor[rgb]{0.161,0.373,0.58}{\textbf{#1}}}%
\newcommand{\hlkwb}[1]{\textcolor[rgb]{0.69,0.353,0.396}{#1}}%
\newcommand{\hlkwc}[1]{\textcolor[rgb]{0.333,0.667,0.333}{#1}}%
\newcommand{\hlkwd}[1]{\textcolor[rgb]{0.737,0.353,0.396}{\textbf{#1}}}%
\let\hlipl\hlkwb

\usepackage{framed}
\makeatletter
\newenvironment{kframe}{%
 \def\at@end@of@kframe{}%
 \ifinner\ifhmode%
  \def\at@end@of@kframe{\end{minipage}}%
  \begin{minipage}{\columnwidth}%
 \fi\fi%
 \def\FrameCommand##1{\hskip\@totalleftmargin \hskip-\fboxsep
 \colorbox{shadecolor}{##1}\hskip-\fboxsep
     % There is no \\@totalrightmargin, so:
     \hskip-\linewidth \hskip-\@totalleftmargin \hskip\columnwidth}%
 \MakeFramed {\advance\hsize-\width
   \@totalleftmargin\z@ \linewidth\hsize
   \@setminipage}}%
 {\par\unskip\endMakeFramed%
 \at@end@of@kframe}
\makeatother

\definecolor{shadecolor}{rgb}{.97, .97, .97}
\definecolor{messagecolor}{rgb}{0, 0, 0}
\definecolor{warningcolor}{rgb}{1, 0, 1}
\definecolor{errorcolor}{rgb}{1, 0, 0}
\newenvironment{knitrout}{}{} % an empty environment to be redefined in TeX

\usepackage{alltt}
\usepackage[margin=1.0in]{geometry} % To set margins
\usepackage{amsmath}  % This allows me to use the align functionality.
                      % If you find yourself trying to replicate
                      % something you found online, ensure you're
                      % loading the necessary packages!
\usepackage{amsfonts} % Math font
\usepackage{fancyvrb}
\usepackage{hyperref} % For including hyperlinks
\usepackage[shortlabels]{enumitem}% For enumerated lists with labels specified
                                  % We had to run tlmgr_install("enumitem") in R
\usepackage{float}    % For telling R where to put a table/figure
\usepackage{natbib}        %For the bibliography
\bibliographystyle{apalike}%For the bibliography
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\begin{document}


\begin{enumerate}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Question 1
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\item A group of researchers is running an experiment over the course of 30 months, 
with a single observation collected at the end of each month. Let $X_1, ..., X_{30}$
denote the observations for each month. From prior studies, the researchers know that
\[X_i \sim f_X(x),\]
but the mean $\mu_X$ is unknown, and they wish to conduct the following test
\begin{align*}
H_0&: \mu_X = 0\\
H_a&: \mu_X > 0.
\end{align*}
At month $k$, they have accumulated data $X_1, ..., X_k$ and they have the 
$t$-statistic
\[T_k = \frac{\bar{X} - 0}{S_k/\sqrt{n}}.\]
The initial plan was to test the hypotheses after all data was collected (at the 
end of month 30), at level $\alpha=0.05$. However, conducting the experiment is 
expensive, so the researchers want to ``peek" at the data at the end of month 20 
to see if they can stop it early. That is, the researchers propose to check 
whether $t_{20}$ provides statistically discernible support for the alternative. 
If it does, they will stop the experiment early and report support for the 
researcher's alternative hypothesis. If it does not, they will continue to month 
30 and test whether $t_{30}$ provides statistically discernible support for the
alternative.

\begin{enumerate}
  \item What values of $t_{20}$ provide statistically discernible support for the
  alternative hypothesis?
  
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hldef{alpha} \hlkwb{=} \hlnum{0.05}
\hldef{m20} \hlkwb{=} \hlnum{20}
\hldef{discernible_boundary_lower} \hlkwb{=} \hlkwd{qt}\hldef{(alpha}\hlopt{/}\hlnum{2}\hldef{,} \hlkwc{df} \hldef{= m20}\hlopt{-}\hlnum{1}\hldef{)}
\hldef{discernible_boundary_upper} \hlkwb{=} \hlkwd{qt}\hldef{(}\hlnum{1}\hlopt{-}\hldef{alpha}\hlopt{/}\hlnum{2}\hldef{,} \hlkwc{df} \hldef{= m20}\hlopt{-}\hlnum{1}\hldef{)}

\hldef{discernible_boundary_lower}
\end{alltt}
\begin{verbatim}
## [1] -2.093024
\end{verbatim}
\begin{alltt}
\hldef{discernible_boundary_upper}
\end{alltt}
\begin{verbatim}
## [1] 2.093024
\end{verbatim}
\end{kframe}
\end{knitrout}
  
  If $t_{20} > 2.093024$, then there is statistically discernible support for the alternative and we would reject the null.
  
  \item What values of $t_{30}$ provide statistically discernible support for the
  alternative hypothesis?
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hldef{alpha} \hlkwb{=} \hlnum{0.05}
\hldef{m30} \hlkwb{=} \hlnum{30}
\hldef{boundary_lower} \hlkwb{=} \hlkwd{qt}\hldef{(alpha}\hlopt{/}\hlnum{2}\hldef{,} \hlkwc{df} \hldef{= m30}\hlopt{-}\hlnum{1}\hldef{)}
\hldef{boundary_upper} \hlkwb{=} \hlkwd{qt}\hldef{(}\hlnum{1}\hlopt{-}\hldef{alpha}\hlopt{/}\hlnum{2}\hldef{,} \hlkwc{df} \hldef{= m30}\hlopt{-}\hlnum{1}\hldef{)}

\hldef{boundary_lower}
\end{alltt}
\begin{verbatim}
## [1] -2.04523
\end{verbatim}
\begin{alltt}
\hldef{boundary_upper}
\end{alltt}
\begin{verbatim}
## [1] 2.04523
\end{verbatim}
\end{kframe}
\end{knitrout}
  If $t_{30} > 2.04523$, then there is statistically discernible support for the alternative and we would reject the null.
  
  \item Suppose $f_X(x)$ is a Laplace distribution with $a=0$ and $b=4.0$.
  Conduct a simulation study to assess the Type I error rate of this approach.\\
  \textbf{Note:} You can use the \texttt{rlaplace()} function from the \texttt{VGAM}
  package for \texttt{R} \citep{VGAM}.
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlkwd{library}\hldef{(VGAM)}
\hlcom{#??rlaplace}
\hldef{alpha} \hlkwb{=} \hlnum{0.05}
\hldef{m20} \hlkwb{=} \hlnum{20}
\hldef{m30} \hlkwb{=} \hlnum{30}
\hldef{t_20} \hlkwb{=} \hlkwd{qt}\hldef{(}\hlnum{1}\hlopt{-}\hldef{alpha,} \hlkwc{df} \hldef{= m20}\hlopt{-}\hlnum{1}\hldef{)}
\hldef{t_30} \hlkwb{=} \hlkwd{qt}\hldef{(}\hlnum{1}\hlopt{-}\hldef{alpha,} \hlkwc{df} \hldef{= m30}\hlopt{-}\hlnum{1}\hldef{)}

\hldef{simu_type1} \hlkwb{=} \hlkwa{function}\hldef{(}\hlkwc{N} \hldef{=} \hlnum{10000}\hldef{,} \hlkwc{b} \hldef{=} \hlnum{4}\hldef{)\{}
  \hldef{false_positives} \hlkwb{=} \hlnum{0}
  \hlkwa{for} \hldef{(i} \hlkwa{in} \hlnum{1}\hlopt{:}\hldef{N)\{}
    \hldef{x} \hlkwb{=} \hlkwd{rlaplace}\hldef{(}\hlnum{30}\hldef{,} \hlkwc{location} \hldef{=} \hlnum{0}\hldef{,} \hlkwc{scale} \hldef{= b)}
    \hldef{x20} \hlkwb{=} \hldef{x[}\hlnum{1}\hlopt{:}\hlnum{20}\hldef{]}
    \hldef{t20} \hlkwb{=} \hldef{(}\hlkwd{mean}\hldef{(x20)} \hlopt{-} \hlnum{0}\hldef{)} \hlopt{/} \hldef{(}\hlkwd{sd}\hldef{(x20)}\hlopt{/}\hlkwd{sqrt}\hldef{(}\hlnum{20}\hldef{))} \hlcom{# Centered at 0 so mu = 0}

    \hlkwa{if} \hldef{(t20} \hlopt{>} \hldef{t_20)\{}
      \hldef{false_positives} \hlkwb{=} \hldef{false_positives} \hlopt{+} \hlnum{1}
    \hldef{\}}
    \hlkwa{else} \hldef{\{}
      \hldef{t30} \hlkwb{=} \hldef{(}\hlkwd{mean}\hldef{(x)} \hlopt{-} \hlnum{0}\hldef{)} \hlopt{/} \hldef{(}\hlkwd{sd}\hldef{(x)}\hlopt{/}\hlkwd{sqrt}\hldef{(}\hlnum{30}\hldef{))}
      \hlkwa{if} \hldef{(t30} \hlopt{>} \hldef{t_30)\{}
        \hldef{false_positives} \hlkwb{=} \hldef{false_positives} \hlopt{+} \hlnum{1}
      \hldef{\}}
    \hldef{\}}
  \hldef{\}}
  \hlkwd{return}\hldef{(false_positives} \hlopt{/} \hldef{N)}
\hldef{\}}

\hldef{type1_rate} \hlkwb{=} \hlkwd{simu_type1}\hldef{()}
\hldef{type1_rate}
\end{alltt}
\begin{verbatim}
## [1] 0.0732
\end{verbatim}
\end{kframe}
\end{knitrout}
  
  The Type I error rate for this approach is $0.0735$ or $7.35\%$
  
  \item \textbf{Optional Challenge:} Can you find a value of $\alpha<0.05$ that yields a 
  Type I error rate of 0.05?
\end{enumerate}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Question 2
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  \item Perform a simulation study to assess the robustness of the $T$ test. 
  Specifically, generate samples of size $n=15$ from the Beta(10,2), Beta(2,10), 
  and Beta(10,10) distributions and conduct the following hypothesis tests against 
  the actual mean for each case (e.g., $\frac{10}{10+2}$, $\frac{2}{10+2}$, and 
  $\frac{10}{10+10}$). 
  \begin{enumerate}
    \item What proportion of the time do we make an error of Type I for a
    left-tailed test?
    \item What proportion of the time do we make an error of Type I for a
    right-tailed test?
    \item What proportion of the time do we make an error of Type I for a
    two-tailed test?
    \item How does skewness of the underlying population distribution effect
    Type I error across the test types?
  \end{enumerate}
  
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hldef{t_test_errors} \hlkwb{=} \hlkwa{function}\hldef{(}\hlkwc{N} \hldef{=} \hlnum{10000}\hldef{,} \hlkwc{func}\hldef{,} \hlkwc{true_mean}\hldef{,} \hlkwc{n} \hldef{=} \hlnum{15}\hldef{)\{}
  \hldef{left_error} \hlkwb{=} \hlnum{0}
  \hldef{right_error} \hlkwb{=} \hlnum{0}
  \hldef{two_error} \hlkwb{=} \hlnum{0}

  \hlkwa{for} \hldef{(i} \hlkwa{in} \hlnum{1}\hlopt{:}\hldef{N)\{}
    \hldef{x} \hlkwb{=} \hlkwd{func}\hldef{(n)}
    \hldef{t_stat} \hlkwb{=} \hldef{(}\hlkwd{mean}\hldef{(x)} \hlopt{-} \hldef{true_mean)} \hlopt{/} \hldef{(}\hlkwd{sd}\hldef{(x)} \hlopt{/} \hlkwd{sqrt}\hldef{(n))}
    \hlkwa{if} \hldef{(t_stat} \hlopt{<} \hlkwd{qt}\hldef{(}\hlnum{0.05}\hldef{,} \hlkwc{df} \hldef{= n} \hlopt{-} \hlnum{1}\hldef{))\{} \hlcom{# Checks the left-tailed test error rate}
      \hldef{left_error} \hlkwb{=} \hldef{left_error} \hlopt{+} \hlnum{1}
    \hldef{\}}
    \hlkwa{if} \hldef{(t_stat} \hlopt{>} \hlkwd{qt}\hldef{(}\hlnum{0.95}\hldef{,} \hlkwc{df} \hldef{= n} \hlopt{-} \hlnum{1}\hldef{))\{}
      \hldef{right_error} \hlkwb{=} \hldef{right_error} \hlopt{+} \hlnum{1}
    \hldef{\}}
    \hlkwa{if}\hldef{(}\hlkwd{abs}\hldef{(t_stat)} \hlopt{>} \hlkwd{qt}\hldef{(}\hlnum{0.975}\hldef{,} \hlkwc{df} \hldef{= n} \hlopt{-} \hlnum{1}\hldef{))\{}
      \hldef{two_error} \hlkwb{=} \hldef{two_error} \hlopt{+} \hlnum{1}
    \hldef{\}}
  \hldef{\}}
  \hlkwd{return}\hldef{(}\hlkwd{c}\hldef{(}\hlsng{"Left-tailed"} \hldef{= left_error}\hlopt{/}\hldef{N,}
           \hlsng{"Right-tailed"} \hldef{= right_error}\hlopt{/}\hldef{N,}
           \hlsng{"Two-tailed"} \hldef{= two_error}\hlopt{/}\hldef{N))}
\hldef{\}}
\hlkwd{set.seed}\hldef{(}\hlnum{1313}\hldef{)}
\hldef{beta_10_2} \hlkwb{=} \hlkwd{t_test_errors}\hldef{(}\hlkwc{func} \hldef{=} \hlkwa{function}\hldef{(}\hlkwc{n}\hldef{)} \hlkwd{rbeta}\hldef{(n,} \hlnum{10}\hldef{,}\hlnum{2}\hldef{),} \hlkwc{true_mean} \hldef{=} \hlnum{10}\hlopt{/}\hlnum{12}\hldef{)}
\hldef{beta_2_10} \hlkwb{=} \hlkwd{t_test_errors}\hldef{(}\hlkwc{func} \hldef{=} \hlkwa{function}\hldef{(}\hlkwc{n}\hldef{)} \hlkwd{rbeta}\hldef{(n,} \hlnum{2}\hldef{,} \hlnum{10}\hldef{),} \hlkwc{true_mean} \hldef{=} \hlnum{2}\hlopt{/}\hlnum{12}\hldef{)}
\hldef{beta_10_10} \hlkwb{=} \hlkwd{t_test_errors}\hldef{(}\hlkwc{func} \hldef{=} \hlkwa{function}\hldef{(}\hlkwc{n}\hldef{)} \hlkwd{rbeta}\hldef{(n,} \hlnum{10}\hldef{,} \hlnum{10}\hldef{),} \hlkwc{true_mean} \hldef{=} \hlnum{10}\hlopt{/}\hlnum{20}\hldef{)}

\hldef{beta_10_2}
\end{alltt}
\begin{verbatim}
##  Left-tailed Right-tailed   Two-tailed 
##       0.0300       0.0804       0.0619
\end{verbatim}
\begin{alltt}
\hldef{beta_2_10}
\end{alltt}
\begin{verbatim}
##  Left-tailed Right-tailed   Two-tailed 
##       0.0831       0.0318       0.0624
\end{verbatim}
\begin{alltt}
\hldef{beta_10_10}
\end{alltt}
\begin{verbatim}
##  Left-tailed Right-tailed   Two-tailed 
##       0.0506       0.0532       0.0518
\end{verbatim}
\end{kframe}
\end{knitrout}
\begin{enumerate}
  \item For Beta($10, 2$) distribution, the right-tailed test has a higher Type I error rate of $8.04\%$, while the left-tailed test has a lower error rate of $3\%$.
  \item The Beta($2, 10$) distribution has a right-tailed test Type I error rate of $3.18\%$ whereas the left-tailed test has an $8.31\%$ error rate.
  \item The Beta($10, 10$) distribution has near equal Type I error rates for the right-tailed and left-tailed tests at about $5\%$.
  \item The skewness of the distributions distort the Type I error rates, particularly for the one-sided tests. In contrast, two-tailed test error rates, which all remained relatively close to $6\%$, seem to produce the least distorted Type I error rates for various skewed distributions. This suggests that two-tailed tests may give more reliable Type I error rates. 
\end{enumerate}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% End Document
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\end{enumerate}
\bibliography{bibliography}
\end{document}

